# Generated by Django 5.1.3 on 2025-03-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
