# Generated by Django 5.1.3 on 2025-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
