# Generated by Django 5.1.3 on 2025-03-18 15:40

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_chatmessage_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание курса')),
                ('category', models.CharField(default='Без категории', max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='course_videos/', verbose_name='Видео (файл)')),
                ('video_des', models.TextField(blank=True, null=True, verbose_name='Описание к видео')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/', verbose_name='Файл')),
                ('course_it', ckeditor.fields.RichTextField(default='', verbose_name='Сам курс')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
        ),
    ]
