# Generated by Django 5.1.3 on 2025-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-18 12:00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
