# Generated by Django 5.1.3 on 2025-03-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_course_question_answer_test_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='learn.courses'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
