# Generated by Django 5.1.3 on 2025-03-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_alter_message_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.CASCADE, to='learn.category', verbose_name='Категория'),
        ),
    ]
